server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      uri: http://localhost:8888

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: ranking-service
          uri: lb://RANKING-SERVICE
          predicates:
            - Path=/api/**

        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/reportes/**
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
