server:
  port: 0

spring:
  application:
    name: ranking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/examen2
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
